//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CHQ10Entities1 : DbContext
    {
        public CHQ10Entities1(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DANHMUCKHOANTDV> TBL_DANHMUCKHOANTDV { get; set; }
        public virtual DbSet<TBL_DANHMUCKHOANTDV_PHI> TBL_DANHMUCKHOANTDV_PHI { get; set; }
        public virtual DbSet<DTA_TONKHO_NHAP> DTA_TONKHO_NHAP { get; set; }
        public virtual DbSet<DS_TDV_PTTT> DS_TDV_PTTT { get; set; }
        public virtual DbSet<DTA_DONDATHANG> DTA_DONDATHANG { get; set; }
        public virtual DbSet<TBL_DANHMUCBIENBANTHOATHUAN> TBL_DANHMUCBIENBANTHOATHUAN { get; set; }
    }
}
