//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIEUHUONG
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public string DataBase { get; set; }
        public string UserID { get; set; }
        public string Pass { get; set; }
        public string ChiNhanh { get; set; }
    }
}
