//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_TDV_PTTT
    {
        public string MaTDV { get; set; }
        public string TenTDV { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<bool> CL { get; set; }
        public string SP { get; set; }
        public string MATINH { get; set; }
        public Nullable<bool> tdv { get; set; }
        public string MANV { get; set; }
        public string idlocal { get; set; }
        public string idglobal { get; set; }
        public string idglobal_supervisor { get; set; }
        public string idglobal_manager { get; set; }
        public string idglobal_director { get; set; }
        public string idglobal_region { get; set; }
    }
}
