//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_PHATSINHCO131
    {
        public string macn { get; set; }
        public string tencn { get; set; }
        public string sct { get; set; }
        public System.DateTime ngayct { get; set; }
        public string noidung { get; set; }
        public string tkn { get; set; }
        public string makhn { get; set; }
        public string tkc { get; set; }
        public string makhc { get; set; }
        public Nullable<decimal> tien { get; set; }
        public string phanloai { get; set; }
        public string phanloaikhachhang { get; set; }
        public Nullable<System.DateTime> ngayupdate { get; set; }
        public string phanloaiotcetc { get; set; }
    }
}
