//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_CT_HOADON_XUAT
    {
        public Nullable<bool> KTKM { get; set; }
        public Nullable<bool> KT { get; set; }
        public string SoHD { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public string MaCH { get; set; }
        public string MaHH { get; set; }
        public string TenHH { get; set; }
        public string DVT { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<double> TyLeCK { get; set; }
        public string MaLo { get; set; }
        public string HanDung { get; set; }
        public int stt { get; set; }
        public string MAKM { get; set; }
        public Nullable<decimal> DONGIA_VAT { get; set; }
        public string GHICHU { get; set; }
        public string DOWN { get; set; }
        public Nullable<bool> KT_KHO { get; set; }
        public string KHO { get; set; }
        public string SODK { get; set; }
        public string MACTHT { get; set; }
    }
}
