//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_HOADON_XUAT
    {
        public string SoHD { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public string MaPL { get; set; }
        public string MaKH { get; set; }
        public string MaTDV { get; set; }
        public string MaTinh { get; set; }
        public string DONVI { get; set; }
        public string MATT { get; set; }
        public string MATHUE { get; set; }
        public string MaCH { get; set; }
        public Nullable<int> ThueSuat { get; set; }
        public Nullable<decimal> tienvat { get; set; }
        public Nullable<decimal> tienck { get; set; }
        public Nullable<decimal> thanhtien_hd { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<System.DateTime> NGAYGIAOHANG { get; set; }
        public string TENNGUOIGD { get; set; }
        public string DIACHI { get; set; }
        public string HOPDONG { get; set; }
        public string kihieu { get; set; }
        public Nullable<bool> kt { get; set; }
        public string TIENCKKM { get; set; }
        public string CTGS { get; set; }
        public Nullable<System.DateTime> NGAYCTGS { get; set; }
        public string PPTT { get; set; }
        public Nullable<System.DateTime> ngaytt { get; set; }
        public string PL { get; set; }
        public string nhaptaikho { get; set; }
        public string txttien { get; set; }
        public Nullable<bool> KT_CANDOI { get; set; }
        public Nullable<bool> KT_CHANLE { get; set; }
        public string SOHDM { get; set; }
        public Nullable<System.DateTime> NGAYLAPHDM { get; set; }
        public Nullable<bool> approval { get; set; }
        public string ghichu_approval { get; set; }
        public Nullable<System.DateTime> ngayxuly { get; set; }
        public string SOHD_DT { get; set; }
        public Nullable<int> LAN { get; set; }
        public Nullable<bool> HETNO { get; set; }
        public Nullable<decimal> TIEN_PHI { get; set; }
        public Nullable<bool> TT1 { get; set; }
        public Nullable<decimal> TIEN_TT1 { get; set; }
        public Nullable<bool> TT2 { get; set; }
        public Nullable<decimal> TIEN_TT2 { get; set; }
        public string NGUOINHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public Nullable<System.DateTime> NGAYTRATIEN { get; set; }
    }
}
