//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;

    public partial class DTA_TONKHO_NHAP
    {
        public int thang { get; set; }
        public int nam { get; set; }
        public string kho { get; set; }
        public string mahh { get; set; }
        public string tenhh { get; set; }
        public string dvt { get; set; }
        public string malo { get; set; }
        public string handung { get; set; }
        public Nullable<decimal> slton { get; set; }
        public int trangthai { get; set; }
        public string mach { get; set; }
    }
}
