//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_APAGING
    {
        public System.DateTime ngay { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public Nullable<decimal> cocuoiky { get; set; }
        public Nullable<decimal> overdue { get; set; }
        public Nullable<decimal> today { get; set; }
        public Nullable<decimal> W1_M1 { get; set; }
        public Nullable<decimal> W2_M1 { get; set; }
        public Nullable<decimal> W3_M1 { get; set; }
        public Nullable<decimal> W4_M1 { get; set; }
        public Nullable<decimal> W1_M2 { get; set; }
        public Nullable<decimal> W2_M2 { get; set; }
        public Nullable<decimal> W3_M2 { get; set; }
        public Nullable<decimal> W4_M2 { get; set; }
        public Nullable<decimal> W1_M3 { get; set; }
        public Nullable<decimal> W2_M3 { get; set; }
        public Nullable<decimal> W3_M3 { get; set; }
        public Nullable<decimal> W4_M3 { get; set; }
        public Nullable<decimal> M4 { get; set; }
        public Nullable<decimal> M5 { get; set; }
        public Nullable<decimal> M6 { get; set; }
    }
}
