//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_GIAOHANG
    {
        public string macn { get; set; }
        public string sohd { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string diachi { get; set; }
        public System.DateTime ngayhoadon { get; set; }
        public System.DateTime ngay { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public bool thutien { get; set; }
        public Nullable<bool> giaohang { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public string nguoigiaohang { get; set; }
        public string taikhoan { get; set; }
        public string matdv { get; set; }
        public string lido { get; set; }
        public string taikhoanphan { get; set; }
    }
}
