//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_SOTHE
    {
        public string macn { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public int qui { get; set; }
        public string matdv { get; set; }
        public int sothe { get; set; }
        public string nguoitao { get; set; }
        public System.DateTime ngaytao { get; set; }
        public int nam { get; set; }
    }
}
