//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_CONGTACTRINHDUOC
    {
        public string macn { get; set; }
        public string matdv { get; set; }
        public System.DateTime ngay { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public Nullable<bool> checkin { get; set; }
        public Nullable<int> ketqua { get; set; }
        public string ghichu { get; set; }
        public string ketqua_text { get; set; }
        public Nullable<bool> khoa { get; set; }
        public Nullable<bool> checkgps { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public int id { get; set; }
    }
}
