//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_KEHOACHCONGNO
    {
        public string MACN { get; set; }
        public int THANG { get; set; }
        public int NAM { get; set; }
        public System.DateTime TUNGAY { get; set; }
        public System.DateTime DENNGAY { get; set; }
        public string MAKH { get; set; }
        public string TENKH { get; set; }
        public string PHANLOAI { get; set; }
        public string MATDV { get; set; }
        public Nullable<decimal> TIENTHU { get; set; }
        public string GIAITRINH { get; set; }
        public string NGAY { get; set; }
        public string NGUOIDUNG { get; set; }
        public Nullable<System.DateTime> NGAYTAO { get; set; }
    }
}
