//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_TOADOKHACHHANG
    {
        public string macn { get; set; }
        public string makh { get; set; }
        public string tenkh { get; set; }
        public string usernhap { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public Nullable<System.DateTime> lastupdate { get; set; }
    }
}
