//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_XUAT_CHITIET
    {
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public string TENDVBC { get; set; }
        public string MATINH { get; set; }
        public string QUANHUYEN { get; set; }
        public string MIEN { get; set; }
        public string PHANLOAIHD { get; set; }
        public string PHANLOAI { get; set; }
        public string NHOM { get; set; }
        public string MATDV { get; set; }
        public string TENTDV { get; set; }
        public string phanloaikhachhang { get; set; }
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public string MAKH { get; set; }
        public string DONVI { get; set; }
        public string DIACHI { get; set; }
        public Nullable<decimal> DOANHTHUTHUAN { get; set; }
        public Nullable<decimal> DOANHTHU { get; set; }
        public Nullable<double> TIENVAT { get; set; }
        public int id { get; set; }
        public string KENH { get; set; }
    }
}
