//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_KYHANCONGNO
    {
        public System.DateTime NGAY { get; set; }
        public string MACH { get; set; }
        public string MAKH { get; set; }
        public string DONVI { get; set; }
        public string MATINH { get; set; }
        public string PHANLOAI { get; set; }
        public string PHANLOAIKHACHHANG { get; set; }
        public Nullable<decimal> OI_balance { get; set; }
        public Nullable<decimal> D_0_6 { get; set; }
        public Nullable<decimal> D_7_14 { get; set; }
        public Nullable<decimal> D_15_30 { get; set; }
        public Nullable<decimal> D_31_60 { get; set; }
        public Nullable<decimal> D_61_90 { get; set; }
        public Nullable<decimal> D_91_120 { get; set; }
        public Nullable<decimal> D_121_180 { get; set; }
        public Nullable<decimal> D_OVER_180 { get; set; }
        public Nullable<decimal> OI_Balance_Overdue { get; set; }
        public Nullable<decimal> QUAHAN_1_6 { get; set; }
        public Nullable<decimal> QUAHAN_7_14 { get; set; }
        public Nullable<decimal> QUAHAN_15_30 { get; set; }
        public Nullable<decimal> QUAHAN_31_60 { get; set; }
        public Nullable<decimal> QUAHAN_61_90 { get; set; }
        public Nullable<decimal> QUAHAN_91_120 { get; set; }
        public Nullable<decimal> QUAHAN_121_180 { get; set; }
        public Nullable<decimal> QUAHAN_181_360 { get; set; }
        public Nullable<decimal> QUAHAN_361_720 { get; set; }
        public Nullable<decimal> QUAHAN_LON_720 { get; set; }
        public Nullable<decimal> FORECAST_TUAN_1 { get; set; }
        public Nullable<decimal> FORECAST_TUAN_2 { get; set; }
        public Nullable<decimal> T1 { get; set; }
        public Nullable<decimal> T2 { get; set; }
        public Nullable<decimal> T3 { get; set; }
        public Nullable<decimal> T4 { get; set; }
        public Nullable<decimal> T5 { get; set; }
        public Nullable<decimal> T6 { get; set; }
        public Nullable<decimal> T7 { get; set; }
        public Nullable<decimal> T8 { get; set; }
        public Nullable<decimal> T9 { get; set; }
        public Nullable<decimal> T10 { get; set; }
        public Nullable<decimal> T11 { get; set; }
        public Nullable<decimal> T12 { get; set; }
    }
}
