//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_DONDATHANG
    {
        public string MADH { get; set; }
        public System.DateTime NgayDat { get; set; }
        public int STT { get; set; }
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public string DVT { get; set; }
        public string DONVI { get; set; }
        public string MACH { get; set; }
        public string MATDV { get; set; }
        public string MAKH { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> GIABAN_VAT { get; set; }
        public Nullable<int> VAT { get; set; }
        public Nullable<bool> DUYETDH { get; set; }
        public string MACTKM { get; set; }
        public string TENCTKM { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public string SOHD { get; set; }
        public Nullable<System.DateTime> NGAYLAPHD { get; set; }
        public string GHICHU { get; set; }
        public Nullable<double> ck { get; set; }
        public string USERTAO { get; set; }
        public Nullable<System.DateTime> NGAYTHUCHIEN { get; set; }
        public string MACTHT { get; set; }
        public string NGUOIDUYET { get; set; }
        public Nullable<int> SOLUONG2 { get; set; }
        public Nullable<int> SOLUONG3 { get; set; }
        public string LIDO { get; set; }

        public string CN { get; set; }
    }
}
