//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_TONKHO_CHITIET
    {
        public string macn { get; set; }
        public string makho { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public string mahh { get; set; }
        public Nullable<decimal> slton { get; set; }
        public string solo { get; set; }
        public string handung { get; set; }
    }
}
