//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTA_CONGNOHANGNGAY
    {
        public System.DateTime NGAYDAU { get; set; }
        public System.DateTime NGAYCUOI { get; set; }
        public string MACH { get; set; }
        public string MAKH1 { get; set; }
        public string DONVI { get; set; }
        public string MATINH { get; set; }
        public string MATDV { get; set; }
        public string PHANLOAI { get; set; }
        public string PHANLOAIKHACHHANG { get; set; }
        public Nullable<double> OI_balance { get; set; }
        public Nullable<double> OI_Balance_Overdue { get; set; }
        public Nullable<double> QUAHAN_1_30 { get; set; }
        public Nullable<double> QUAHAN_31_60 { get; set; }
        public Nullable<double> QUAHAN_61_120 { get; set; }
        public Nullable<double> QUAHAN_121_360 { get; set; }
        public Nullable<double> QUAHAN_LON_360 { get; set; }
        public Nullable<double> PSCO { get; set; }
        public Nullable<double> PSNO { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> Balance_Overdue { get; set; }
    }
}
