//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KT_THEntities1 : DbContext
    {
        public KT_THEntities1(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_DANHMUCTINH> TBL_DANHMUCTINH { get; set; }
        public virtual DbSet<TBL_DANHMUCSODANGKY> TBL_DANHMUCSODANGKY { get; set; }
        public virtual DbSet<TBL_DANHMUCCHUONGTRINHHOTRO> TBL_DANHMUCCHUONGTRINHHOTRO { get; set; }
        public virtual DbSet<TBL_DANHMUCHANGHOATICHDIEM> TBL_DANHMUCHANGHOATICHDIEM { get; set; }
        public virtual DbSet<DTA_TONKHO_NHAP> DTA_TONKHO_NHAP { get; set; }
        public virtual DbSet<TBL_DANHMUCKHACHHANG_PENDING> TBL_DANHMUCKHACHHANG_PENDING { get; set; }
        public virtual DbSet<TBL_DANHMUCPHANLOAIHD> TBL_DANHMUCPHANLOAIHD { get; set; }
        public virtual DbSet<TBL_DANHMUCNHOMSANPHAM> TBL_DANHMUCNHOMSANPHAM { get; set; }
        public virtual DbSet<TBL_DANHMUCKM_CHITIET> TBL_DANHMUCKM_CHITIET { get; set; }
        public virtual DbSet<TBL_DANHMUCKM> TBL_DANHMUCKM { get; set; }
        public virtual DbSet<TBL_DANHMUCCHUONGTRINHHOTRO_CHITIET> TBL_DANHMUCCHUONGTRINHHOTRO_CHITIET { get; set; }
        public virtual DbSet<dta_Products> dta_Products { get; set; }
        public virtual DbSet<dta_Products_pending> dta_Products_pending { get; set; }
    }
}
