//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POWERBIEntities : DbContext
    {
        public POWERBIEntities()
            : base("name=POWERBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_THANG> TBL_THANG { get; set; }
        public virtual DbSet<TBL_TOPN> TBL_TOPN { get; set; }
        public virtual DbSet<TBL_DANHMUCHANGHOACHUNG> TBL_DANHMUCHANGHOACHUNG { get; set; }
        public virtual DbSet<TBL_DANHMUCTINH> TBL_DANHMUCTINH { get; set; }
        public virtual DbSet<TBL_GIAKEKHAI_TAM> TBL_GIAKEKHAI_TAM { get; set; }
        public virtual DbSet<DTA_TONKHO> DTA_TONKHO { get; set; }
        public virtual DbSet<DTA_NHAP_CHITIET> DTA_NHAP_CHITIET { get; set; }
        public virtual DbSet<DTA_TONKHO_CHITIET> DTA_TONKHO_CHITIET { get; set; }
        public virtual DbSet<DTA_XUAT_CHITIET> DTA_XUAT_CHITIET { get; set; }
        public virtual DbSet<TBL_THOIGIAN_CHITIET> TBL_THOIGIAN_CHITIET { get; set; }
        public virtual DbSet<DTA_XUAT_CHITIET_HOADON> DTA_XUAT_CHITIET_HOADON { get; set; }
        public virtual DbSet<TBL_THOIGIAN_CHITIET_HOADON> TBL_THOIGIAN_CHITIET_HOADON { get; set; }
        public virtual DbSet<DTA_DONDATHANG> DTA_DONDATHANG { get; set; }
        public virtual DbSet<TBL_DANHMUCHOPDONG> TBL_DANHMUCHOPDONG { get; set; }
        public virtual DbSet<TBL_THOIGIAN_KYHANNO> TBL_THOIGIAN_KYHANNO { get; set; }
        public virtual DbSet<DTA_KYHANCONGNO> DTA_KYHANCONGNO { get; set; }
        public virtual DbSet<TBL_DANHMUCTDV_GLOBALID> TBL_DANHMUCTDV_GLOBALID { get; set; }
        public virtual DbSet<DTA_KEHOACHCONGNO> DTA_KEHOACHCONGNO { get; set; }
        public virtual DbSet<TBL_CUSTOMER_CHANNEL> TBL_CUSTOMER_CHANNEL { get; set; }
        public virtual DbSet<DTA_CONGNOHANGNGAY> DTA_CONGNOHANGNGAY { get; set; }
        public virtual DbSet<TBL_THOIGIAN_CONGNOHANGNGAY> TBL_THOIGIAN_CONGNOHANGNGAY { get; set; }
        public virtual DbSet<TBL_CT_DANHMUCHOPDONG> TBL_CT_DANHMUCHOPDONG { get; set; }
        public virtual DbSet<DTA_PHATSINHCO131> DTA_PHATSINHCO131 { get; set; }
        public virtual DbSet<DTA_APAGING> DTA_APAGING { get; set; }
        public virtual DbSet<TBL_PHIEUTHUHANGNGAY> TBL_PHIEUTHUHANGNGAY { get; set; }
    }
}
