//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCEntities : DbContext
    {
        public SCEntities()
            : base("name=SCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_BINHLUAN> TBL_BINHLUAN { get; set; }
        public virtual DbSet<TBL_CHITIETPHANQUYEN> TBL_CHITIETPHANQUYEN { get; set; }
        public virtual DbSet<TBL_DEMANDFC> TBL_DEMANDFC { get; set; }
        public virtual DbSet<TBL_DEMANFC_AUDIT> TBL_DEMANFC_AUDIT { get; set; }
        public virtual DbSet<TBL_KENH> TBL_KENH { get; set; }
        public virtual DbSet<TBL_PHANQUYEN> TBL_PHANQUYEN { get; set; }
        public virtual DbSet<TBL_QLSXAPPROVE> TBL_QLSXAPPROVE { get; set; }
        public virtual DbSet<TBL_SALEAPPROVE> TBL_SALEAPPROVE { get; set; }
        public virtual DbSet<TBL_SCAPPROVE> TBL_SCAPPROVE { get; set; }
    }
}
