//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_QUANLYDANGNHAP
    {
        public System.DateTime Ngay { get; set; }
        public string Username { get; set; }
        public int id { get; set; }
        public string IP { get; set; }
        public string pcname { get; set; }
        public string systemversion { get; set; }
    }
}
