//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCPHUPHI
    {
        public int qui { get; set; }
        public int nam { get; set; }
        public string macn { get; set; }
        public string vitri { get; set; }
        public string phanloai { get; set; }
        public Nullable<decimal> phuphicodinh { get; set; }
        public Nullable<decimal> thang90 { get; set; }
        public Nullable<decimal> thang100 { get; set; }
        public Nullable<decimal> thang110 { get; set; }
        public Nullable<decimal> thang120 { get; set; }
        public Nullable<decimal> quy100 { get; set; }
        public Nullable<decimal> datthang { get; set; }
        public Nullable<decimal> tiledat { get; set; }
    }
}
