//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCHOPDONG
    {
        public string MACN { get; set; }
        public string MAKH { get; set; }
        public string MAHD { get; set; }
        public string noidung { get; set; }
        public Nullable<System.DateTime> NGAYBATDAU { get; set; }
        public Nullable<System.DateTime> NGAYKETTHUC { get; set; }
        public string giatri { get; set; }
        public string donvi { get; set; }
        public Nullable<double> ck { get; set; }
        public string phuluc { get; set; }
        public string nguoidung { get; set; }
        public string MAQD { get; set; }
        public string TENQD { get; set; }
        public Nullable<System.DateTime> NGAYQD { get; set; }
        public string LOAIHD { get; set; }
        public Nullable<bool> KT { get; set; }
        public string GHICHU { get; set; }
    }
}
