//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CUSTOMER_CHANNEL
    {
        public string PHANLOAI { get; set; }
        public string phanloaikhachhang { get; set; }
        public string KENH { get; set; }
        public int id { get; set; }
    }
}
