//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKEHOACH
    {
        public string macn { get; set; }
        public int nam { get; set; }
        public Nullable<decimal> OTC { get; set; }
        public Nullable<decimal> ETC { get; set; }
    
        public virtual TBL_DANHSACHCHINHANH TBL_DANHSACHCHINHANH { get; set; }
    }
}
