//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PHIEUTHUHANGNGAY
    {
        public int id { get; set; }
        public string sct { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public string tkn { get; set; }
        public string makhn { get; set; }
        public string tkc { get; set; }
        public string makhc { get; set; }
        public Nullable<double> tien { get; set; }
        public string nguoidung { get; set; }
        public string macn { get; set; }
    }
}
