//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKM_QUATANG
    {
        public string MACTKM { get; set; }
        public Nullable<bool> CONGDON { get; set; }
        public decimal DIEUKIEN { get; set; }
        public string QUATANG { get; set; }
        public Nullable<decimal> SLQUATANG { get; set; }
        public string QUATANGTHEM { get; set; }
        public Nullable<decimal> SLQUATANGTHEM { get; set; }
        public string QUATANGTHEM1 { get; set; }
        public Nullable<decimal> SLQUATANGTHEM1 { get; set; }
        public Nullable<decimal> TILE { get; set; }
        public Nullable<decimal> GIATRI { get; set; }
    }
}
