//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHSACHCHINHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_DANHSACHCHINHANH()
        {
            this.TBL_DANHMUCKEHOACH = new HashSet<TBL_DANHMUCKEHOACH>();
        }
    
        public string macn { get; set; }
        public string Tencn { get; set; }
        public string Mien { get; set; }
        public Nullable<double> stt { get; set; }
        public Nullable<bool> check { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_DANHMUCKEHOACH> TBL_DANHMUCKEHOACH { get; set; }
    }
}
