//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKHOANTDV
    {
        public int thang { get; set; }
        public int qui { get; set; }
        public int nam { get; set; }
        public string matdv { get; set; }
        public string phanloai { get; set; }
        public string matdvtotruong { get; set; }
        public Nullable<decimal> dskhoan { get; set; }
        public Nullable<decimal> thuchien { get; set; }
        public string idlocal { get; set; }
        public string idglobal { get; set; }
        public string idglobal_supervisor { get; set; }
        public string idglobal_manager { get; set; }
        public string idglobal_director { get; set; }
        public string idglobal_region { get; set; }
        public Nullable<bool> khoa { get; set; }
        public System.DateTime ngay { get; set; }
        public string usertao { get; set; }
        public string macn { get; set; }
        public Nullable<double> tyle { get; set; }
        public Nullable<double> phi { get; set; }
    }
}
