//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKHACHHANGPHANPHOI
    {
        public string macn { get; set; }
        public string makh { get; set; }
        public string donvi { get; set; }
        public string diachi { get; set; }
        public string tennguoilh { get; set; }
        public string matdv { get; set; }
        public string dt { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
    }
}
