//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCLOAIBAOCAO
    {
        public int ID { get; set; }
        public string TENBC { get; set; }
        public string REPORT { get; set; }
        public Nullable<bool> RUTGON { get; set; }
    }
}
