//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CT_DANHMUCHOPDONG
    {
        public string MACN { get; set; }
        public string MAKH { get; set; }
        public string MAHD { get; set; }
        public string MAHH { get; set; }
        public string SODK { get; set; }
        public Nullable<decimal> GIASP { get; set; }
        public Nullable<int> PHI { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    }
}
