//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCTDV
    {
        public string MaTDV { get; set; }
        public string TenTDV { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<bool> TDV { get; set; }
        public string makt { get; set; }
        public Nullable<bool> nghiviec { get; set; }
        public Nullable<System.DateTime> Ngaynghiviec { get; set; }
        public string idlocal { get; set; }
        public string idglobal { get; set; }
        public string idglobal_supervisor { get; set; }
        public string idglobal_manager { get; set; }
        public string idglobal_director { get; set; }
        public string idglobal_region { get; set; }
    }
}
