//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCBIENBANTHOATHUAN
    {
        public int nam { get; set; }
        public string makh { get; set; }
        public string donvi { get; set; }
        public string diachi { get; set; }
        public string phanloaikhachhang { get; set; }
        public string matdv { get; set; }
        public Nullable<double> hanmuc { get; set; }
        public Nullable<double> Q1 { get; set; }
        public Nullable<double> Q2 { get; set; }
        public Nullable<double> Q3 { get; set; }
        public Nullable<double> Q4 { get; set; }
        public Nullable<double> ngayno { get; set; }
        public Nullable<double> ck { get; set; }
        public Nullable<double> ckvuot { get; set; }
        public Nullable<double> ckdat { get; set; }
        public Nullable<bool> kt { get; set; }
    }
}
