//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DSKHOAN
    {
        public string tencn { get; set; }
        public string matinh { get; set; }
        public Nullable<decimal> doanhso { get; set; }
        public Nullable<int> nam { get; set; }
        public string macn { get; set; }
    }
}
