//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BINHLUAN
    {
        public int id { get; set; }
        public string nguoitao { get; set; }
        public int thangduuoc { get; set; }
        public int namduuoc { get; set; }
        public string nguoibinhluan { get; set; }
        public string noidung { get; set; }
        public System.DateTime thoigiantao { get; set; }
    }
}
