//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class TBL_DANHMUCKM
    {
        public string MACTKM { get; set; }
        public string TENCTKM { get; set; }
        public Nullable<System.DateTime> ngaybatdau { get; set; }
        public Nullable<System.DateTime> ngayketthuc { get; set; }
        public string MAHH { get; set; }
        public string GIA { get; set; }
        public string PHAMVI { get; set; }
        public Nullable<decimal> HANMUC { get; set; }
        public Nullable<int> TICHDIEM { get; set; }
        public string GHICHU { get; set; }
        public byte[] FILEDATA { get; set; }
        public Nullable<double> ck { get; set; }
        public Nullable<bool> BBTT { get; set; }
        [NotMapped]

        public List<string> list_phamvi
        {
            get
            {
                return PHAMVI.Split(',').ToList();
            }
        }
    }
}
