//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKHACHHANG_PENDING
    {
        public string macn { get; set; }
        public string phanloaikhachhang { get; set; }
        public string makh { get; set; }
        public string donvi { get; set; }
        public string diachi { get; set; }
        public string tennguoigd { get; set; }
        public string masothue { get; set; }
        public string matdv { get; set; }
        public string matinh { get; set; }
        public string quanhuyen { get; set; }
        public string ghichu { get; set; }
        public string tk { get; set; }
        public string nhom { get; set; }
        public string SP { get; set; }
        public string GIASP { get; set; }
        public string PHI { get; set; }
        public string CP { get; set; }
        public string TAIKHOAN { get; set; }
        public string NGANHANG { get; set; }
        public Nullable<int> ngayno { get; set; }
        public string phanloai { get; set; }
        public Nullable<double> hanmuc { get; set; }
        public string chitiet { get; set; }
        public string xeploai { get; set; }
        public string dt { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public string tinhtrang { get; set; }
        public Nullable<System.DateTime> ngaygddautien { get; set; }
        public Nullable<System.DateTime> ngaygdgannhat { get; set; }
        public Nullable<double> solangd { get; set; }
        public string MACHUNG { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string gioitinh { get; set; }
        public string cmnd { get; set; }
        public Nullable<bool> pheduyet { get; set; }
        public Nullable<System.DateTime> ngayyeucau { get; set; }
        public Nullable<System.DateTime> ngaypheduyet { get; set; }
        public string lydo { get; set; }
        public string GIAYTOPHAPLY { get; set; }
    }
}
