//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCHANGHOACHUNG
    {
        public string mahh { get; set; }
        public string tenhh { get; set; }
        public string dvt { get; set; }
        public string hoatchat { get; set; }
        public string dangbaoche { get; set; }
        public string nhomhang { get; set; }
        public string hamluong { get; set; }
        public string quycach { get; set; }
        public string quycachhop { get; set; }
        public string daidien { get; set; }
        public string sdk { get; set; }
        public Nullable<bool> chc { get; set; }
        public Nullable<decimal> SL1 { get; set; }
        public string DVT1 { get; set; }
        public Nullable<decimal> SL2 { get; set; }
        public string DVT2 { get; set; }
        public Nullable<decimal> SL3 { get; set; }
        public string DVT3 { get; set; }
        public string COPA { get; set; }
        public Nullable<int> giakekhai { get; set; }
    }
}
