//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class TBL_DANHMUCNGUOIDUNG
    {
        public string nguoidung { get; set; }
        public string hoten { get; set; }
        public string matkhau { get; set; }
        public string quyen { get; set; }
        public string phanloai { get; set; }
        public Nullable<bool> READ_ONLY { get; set; }
        public Nullable<bool> PDF { get; set; }
        public Nullable<bool> EXCEL { get; set; }
        public Nullable<bool> WORD { get; set; }
        public string macn { get; set; }
        public string matinh { get; set; }
        public string mahh { get; set; }
        public string matdv { get; set; }
        public Nullable<int> truycap { get; set; }
        public string maquan { get; set; }
        public Nullable<bool> khoatk { get; set; }
        public Nullable<System.DateTime> ngaydoimk { get; set; }
        public Nullable<System.DateTime> ngaydangnhap { get; set; }
        public Nullable<int> dathang { get; set; }
        public string email { get; set; }
        public Nullable<bool> doimk { get; set; }
        public string sdt { get; set; }
        public string resetcode { get; set; }
        public string kho { get; set; }
        public string manhom { get; set; }
        public string poc { get; set; }
        public string loai { get; set; }
        public string makh { get; set; }

        public List<string> chinhanh
        {
            get
            {
                return macn != null ? macn.Split(',').ToList() : new List<string>();
            }
        }
        public virtual TBL_DANHMUCPHANQUYENHCM TBL_DANHMUCPHANQUYENHCM { get; set; }
        public virtual TBL_DANHMUCPHANQUYENKD TBL_DANHMUCPHANQUYENKD { get; set; }
        public virtual TBL_DANHMUCPHANQUYENSC TBL_DANHMUCPHANQUYENSC { get; set; }
        public virtual TBL_DANHMUCPHANQUYENWS TBL_DANHMUCPHANQUYENWS { get; set; }
        public virtual TBL_PHANQUYENCRM TBL_PHANQUYENCRM { get; set; }
    }
}
