//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCSODANGKY
    {
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public string SOLO { get; set; }
        public string SODK { get; set; }
        public string DVT { get; set; }
        public string HANDUNG { get; set; }
        public string NGUOITAO { get; set; }
    }
}
