//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SALEAPPROVE
    {
        public string nguoitao { get; set; }
        public int thangduuoc { get; set; }
        public int namduuoc { get; set; }
        public int thang { get; set; }
        public int nam { get; set; }
        public string mahh { get; set; }
        public string kenh { get; set; }
        public string sub { get; set; }
        public Nullable<int> soluong { get; set; }
        public Nullable<decimal> sotien { get; set; }
        public Nullable<System.DateTime> ngayketthucthau { get; set; }
        public bool khoa { get; set; }
        public System.DateTime ngaytao { get; set; }
    }
}
