//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCKHOANTDV_PHI
    {
        public int thang { get; set; }
        public int nam { get; set; }
        public Nullable<decimal> phuphi_otc { get; set; }
        public Nullable<decimal> phuphi_etc { get; set; }
        public Nullable<decimal> phuphi_supervisor { get; set; }
        public Nullable<decimal> phuphi_manager { get; set; }
        public Nullable<decimal> phuphi_director { get; set; }
        public Nullable<decimal> phuphi_director_sale { get; set; }
    }
}
