//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DANHMUCHANGHOA
    {
        public Nullable<bool> CL { get; set; }
        public string MAHH { get; set; }
        public string TENHH { get; set; }
        public string DVT { get; set; }
        public string nhom { get; set; }
        public string GIAMUA { get; set; }
        public string GIABAN { get; set; }
        public Nullable<bool> KT { get; set; }
        public string QUICACH { get; set; }
        public string tenhoatchat { get; set; }
        public Nullable<decimal> SL1 { get; set; }
        public string DVT1 { get; set; }
        public Nullable<decimal> SL2 { get; set; }
        public string DVT2 { get; set; }
        public Nullable<decimal> SL3 { get; set; }
        public string DVT3 { get; set; }
        public Nullable<bool> HIENTHI { get; set; }
        public string goithau { get; set; }
        public string phi { get; set; }
        public string cp { get; set; }
        public string SDK { get; set; }
        public Nullable<bool> approval { get; set; }
        public string ghichu_approval { get; set; }
        public Nullable<System.DateTime> ngayxuly { get; set; }
        public string nsx { get; set; }
        public Nullable<bool> kiemsoat { get; set; }
        public string hoatchat { get; set; }
        public string dangbaoche { get; set; }
        public string daidien { get; set; }
        public string hamluong { get; set; }
        public string quicachhop { get; set; }
        public Nullable<bool> thauqg { get; set; }
        public Nullable<bool> kedon { get; set; }
        public Nullable<bool> khac { get; set; }
        public Nullable<bool> hm { get; set; }
        public string SODK { get; set; }
        public Nullable<bool> chc { get; set; }
        public string Replacement_code { get; set; }
        public string SAP_code { get; set; }
        public string Classification { get; set; }
        public Nullable<int> GIAKEKHAI { get; set; }
        public string Sub_classification { get; set; }
        public string Therapeutic_area { get; set; }
        public string xuongsx { get; set; }
    }
}
