//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationChart.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationChart.App_LocalResources.GlobalRes", typeof(GlobalRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo BSC.
        /// </summary>
        public static string lbbaocaobsc {
            get {
                return ResourceManager.GetString("lbbaocaobsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báo cáo theo.
        /// </summary>
        public static string lbbaocaotheo {
            get {
                return ResourceManager.GetString("lbbaocaotheo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biểu đồ.
        /// </summary>
        public static string lbbieudo {
            get {
                return ResourceManager.GetString("lbbieudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các bộ lọc.
        /// </summary>
        public static string lbcacboloc {
            get {
                return ResourceManager.GetString("lbcacboloc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cấp lại mật khẩu.
        /// </summary>
        public static string lbcaplaimatkhau {
            get {
                return ResourceManager.GetString("lbcaplaimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào mừng đến với Gateway.
        /// </summary>
        public static string lbchaomung {
            get {
                return ResourceManager.GetString("lbchaomung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string lbchinhanh {
            get {
                return ResourceManager.GetString("lbchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết doanh số.
        /// </summary>
        public static string lbchitietdoanhso {
            get {
                return ResourceManager.GetString("lbchitietdoanhso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết hàng hóa.
        /// </summary>
        public static string lbchitiethanghoa {
            get {
                return ResourceManager.GetString("lbchitiethanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn.
        /// </summary>
        public static string lbchon {
            get {
                return ResourceManager.GetString("lbchon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn chi nhánh.
        /// </summary>
        public static string lbchonchinhanh {
            get {
                return ResourceManager.GetString("lbchonchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có.
        /// </summary>
        public static string lbco {
            get {
                return ResourceManager.GetString("lbco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ít nhất một chữ hoa.
        /// </summary>
        public static string lbcoitnhat1chuhoa {
            get {
                return ResourceManager.GetString("lbcoitnhat1chuhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ít nhất một chứ số.
        /// </summary>
        public static string lbcoitnhat1chuso {
            get {
                return ResourceManager.GetString("lbcoitnhat1chuso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có ít nhất một chữ thường.
        /// </summary>
        public static string lbcoitnhat1chuthuong {
            get {
                return ResourceManager.GetString("lbcoitnhat1chuthuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string lbdangnhap {
            get {
                return ResourceManager.GetString("lbdangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string lbdangxuat {
            get {
                return ResourceManager.GetString("lbdangxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến ngày.
        /// </summary>
        public static string lbdenngay {
            get {
                return ResourceManager.GetString("lbdenngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đến tháng.
        /// </summary>
        public static string lbdenthang {
            get {
                return ResourceManager.GetString("lbdenthang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại liên hệ.
        /// </summary>
        public static string lbdienthoailienhe {
            get {
                return ResourceManager.GetString("lbdienthoailienhe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh số chi tiết.
        /// </summary>
        public static string lbdoanhsochitiet {
            get {
                return ResourceManager.GetString("lbdoanhsochitiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh số phân loại khách hàng.
        /// </summary>
        public static string lbdoanhsophanloaikh {
            get {
                return ResourceManager.GetString("lbdoanhsophanloaikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh số theo tháng.
        /// </summary>
        public static string lbdoanhsotheothang {
            get {
                return ResourceManager.GetString("lbdoanhsotheothang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu chi nhánh.
        /// </summary>
        public static string lbdoanhthuchinhanh {
            get {
                return ResourceManager.GetString("lbdoanhthuchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu hàng tháng.
        /// </summary>
        public static string lbdoanhthuhangthang {
            get {
                return ResourceManager.GetString("lbdoanhthuhangthang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu OTC/ETC.
        /// </summary>
        public static string lbdoanhthuotcetc {
            get {
                return ResourceManager.GetString("lbdoanhthuotcetc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doanh thu vùng miền.
        /// </summary>
        public static string lbdoanhthuvungmien {
            get {
                return ResourceManager.GetString("lbdoanhthuvungmien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Độ dài ít nhất 6 ký tự.
        /// </summary>
        public static string lbdodaiitnhat6kytu {
            get {
                return ResourceManager.GetString("lbdodaiitnhat6kytu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string lbdoimatkhau {
            get {
                return ResourceManager.GetString("lbdoimatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string lbdong {
            get {
                return ResourceManager.GetString("lbdong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng góp ý kiến.
        /// </summary>
        public static string lbdonggopykien {
            get {
                return ResourceManager.GetString("lbdonggopykien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string lbdonvitinh {
            get {
                return ResourceManager.GetString("lbdonvitinh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính : Tỷ đồng.
        /// </summary>
        public static string lbdonvitinhtydong {
            get {
                return ResourceManager.GetString("lbdonvitinhtydong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string lberror {
            get {
                return ResourceManager.GetString("lberror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hãy điền đầy đủ thông tin.
        /// </summary>
        public static string lbhaydiendayduthongtin {
            get {
                return ResourceManager.GetString("lbhaydiendayduthongtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string lbhovaten {
            get {
                return ResourceManager.GetString("lbhovaten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hướng dẫn sử dụng.
        /// </summary>
        public static string lbhuongdansudung {
            get {
                return ResourceManager.GetString("lbhuongdansudung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        public static string lbhuy {
            get {
                return ResourceManager.GetString("lbhuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string lbin {
            get {
                return ResourceManager.GetString("lbin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho.
        /// </summary>
        public static string lbkho {
            get {
                return ResourceManager.GetString("lbkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không.
        /// </summary>
        public static string lbkhong {
            get {
                return ResourceManager.GetString("lbkhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đây là lần đăng nhập đầu tiên. Xin vui lòng đổi mật khẩu !.
        /// </summary>
        public static string lblandaudangnhap {
            get {
                return ResourceManager.GetString("lblandaudangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liên hệ hỗ trợ.
        /// </summary>
        public static string lblienhehotro {
            get {
                return ResourceManager.GetString("lblienhehotro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại báo cáo.
        /// </summary>
        public static string lbloaibaocao {
            get {
                return ResourceManager.GetString("lbloaibaocao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã hàng hóa.
        /// </summary>
        public static string lbmahanghoa {
            get {
                return ResourceManager.GetString("lbmahanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phân loại.
        /// </summary>
        public static string lbmaphanloai {
            get {
                return ResourceManager.GetString("lbmaphanloai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật Khẩu.
        /// </summary>
        public static string lbmatkhau {
            get {
                return ResourceManager.GetString("lbmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu cũ.
        /// </summary>
        public static string lbmatkhaucu {
            get {
                return ResourceManager.GetString("lbmatkhaucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới.
        /// </summary>
        public static string lbmatkhaumoi {
            get {
                return ResourceManager.GetString("lbmatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu mới không được trùng với mật khẩu cũ. Vui lòng thử lại !.
        /// </summary>
        public static string lbmatkhaumoikhongduoctrung {
            get {
                return ResourceManager.GetString("lbmatkhaumoikhongduoctrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miền bắc.
        /// </summary>
        public static string lbmienbac {
            get {
                return ResourceManager.GetString("lbmienbac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miền nam.
        /// </summary>
        public static string lbmiennam {
            get {
                return ResourceManager.GetString("lbmiennam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miền trung.
        /// </summary>
        public static string lbmientrung {
            get {
                return ResourceManager.GetString("lbmientrung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một chi nhánh.
        /// </summary>
        public static string lbmotchinhanh {
            get {
                return ResourceManager.GetString("lbmotchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string lbnam {
            get {
                return ResourceManager.GetString("lbnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string lbngay {
            get {
                return ResourceManager.GetString("lbngay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại chính xác.
        /// </summary>
        public static string lbnhaplaichinhxac {
            get {
                return ResourceManager.GetString("lbnhaplaichinhxac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu cũ không đúng. Vui lòng thử lại !.
        /// </summary>
        public static string lbnhaplaimatkhaukhongdung {
            get {
                return ResourceManager.GetString("lbnhaplaimatkhaukhongdung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu mới.
        /// </summary>
        public static string lbnhaplaimatkhaumoi {
            get {
                return ResourceManager.GetString("lbnhaplaimatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại mật khẩu cũ.
        /// </summary>
        public static string lbnhapmatkhaucu {
            get {
                return ResourceManager.GetString("lbnhapmatkhaucu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mật khẩu mới.
        /// </summary>
        public static string lbnhapmatkhaumoi {
            get {
                return ResourceManager.GetString("lbnhapmatkhaumoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tài khoản.
        /// </summary>
        public static string lbnhaptentaikhoan {
            get {
                return ResourceManager.GetString("lbnhaptentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập tên tài khoản của bạn.
        /// </summary>
        public static string lbnhaptentaikhoan1 {
            get {
                return ResourceManager.GetString("lbnhaptentaikhoan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhiều chi nhánh.
        /// </summary>
        public static string lbnhieuchinhanh {
            get {
                return ResourceManager.GetString("lbnhieuchinhanh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm hàng.
        /// </summary>
        public static string lbnhomhang {
            get {
                return ResourceManager.GetString("lbnhomhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Loại chi tiết khách hàng.
        /// </summary>
        public static string lbphanloaichitietkhachhang {
            get {
                return ResourceManager.GetString("lbphanloaichitietkhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Loại khách hàng.
        /// </summary>
        public static string lbphanloaikhachhang {
            get {
                return ResourceManager.GetString("lbphanloaikhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.Loại khách hàng.
        /// </summary>
        public static string lbplkh {
            get {
                return ResourceManager.GetString("lbplkh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quên mật khẩu.
        /// </summary>
        public static string lbquenmatkhau {
            get {
                return ResourceManager.GetString("lbquenmatkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quí.
        /// </summary>
        public static string lbqui {
            get {
                return ResourceManager.GetString("lbqui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số hóa đơn.
        /// </summary>
        public static string lbsohoadon {
            get {
                return ResourceManager.GetString("lbsohoadon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng nhập.
        /// </summary>
        public static string lbsoluongnhap {
            get {
                return ResourceManager.GetString("lbsoluongnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn.
        /// </summary>
        public static string lbsoluongton {
            get {
                return ResourceManager.GetString("lbsoluongton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn cuối kỳ.
        /// </summary>
        public static string lbsoluongtoncuoiky {
            get {
                return ResourceManager.GetString("lbsoluongtoncuoiky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng tồn đầu kỳ.
        /// </summary>
        public static string lbsoluongtondauky {
            get {
                return ResourceManager.GetString("lbsoluongtondauky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng xuất.
        /// </summary>
        public static string lbsoluongxuat {
            get {
                return ResourceManager.GetString("lbsoluongxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh năm.
        /// </summary>
        public static string lbsosanhnam {
            get {
                return ResourceManager.GetString("lbsosanhnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So sánh theo năm.
        /// </summary>
        public static string lbsosanhtheonam {
            get {
                return ResourceManager.GetString("lbsosanhtheonam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải Excel.
        /// </summary>
        public static string lbtaiexcel {
            get {
                return ResourceManager.GetString("lbtaiexcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string lbtaikhoan {
            get {
                return ResourceManager.GetString("lbtaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản đã bị khóa sau một thời gian dài không sử dụng! Vui lòng liên hệ : &lt;br /&gt; - Phòng Tin Học.
        /// </summary>
        public static string lbtaikhoanbikhoa {
            get {
                return ResourceManager.GetString("lbtaikhoanbikhoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản hoặc mật khẩu không đúng. Vui lòng thử lại !.
        /// </summary>
        public static string lbtaikhoanmatkhausai {
            get {
                return ResourceManager.GetString("lbtaikhoanmatkhausai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải lại.
        /// </summary>
        public static string lbtailai {
            get {
                return ResourceManager.GetString("lbtailai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải PDF.
        /// </summary>
        public static string lbtaipdf {
            get {
                return ResourceManager.GetString("lbtaipdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải về.
        /// </summary>
        public static string lbtaive {
            get {
                return ResourceManager.GetString("lbtaive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải Word.
        /// </summary>
        public static string lbtaiword {
            get {
                return ResourceManager.GetString("lbtaiword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string lbtatca {
            get {
                return ResourceManager.GetString("lbtatca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hàng hóa.
        /// </summary>
        public static string lbtenhanghoa {
            get {
                return ResourceManager.GetString("lbtenhanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi.
        /// </summary>
        public static string lbthaydoi {
            get {
                return ResourceManager.GetString("lbthaydoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo dõi hàng thầu.
        /// </summary>
        public static string lbtheodoihangthau {
            get {
                return ResourceManager.GetString("lbtheodoihangthau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo miền.
        /// </summary>
        public static string lbtheomien {
            get {
                return ResourceManager.GetString("lbtheomien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        public static string lbthongbao {
            get {
                return ResourceManager.GetString("lbthongbao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của tôi.
        /// </summary>
        public static string lbthongtincuatoi {
            get {
                return ResourceManager.GetString("lbthongtincuatoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ doanh thu ETC/OTC.
        /// </summary>
        public static string lbtiledoanhthuetcotc {
            get {
                return ResourceManager.GetString("lbtiledoanhthuetcotc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ doanh thu phân loại khách hàng.
        /// </summary>
        public static string lbtiledoanhthuphanloaikh {
            get {
                return ResourceManager.GetString("lbtiledoanhthuphanloaikh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ doanh thu phân loại khách hàng.
        /// </summary>
        public static string lbtiledoanhthuphanloaikhachhang {
            get {
                return ResourceManager.GetString("lbtiledoanhthuphanloaikhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tỉ lệ doanh thu vùng miền.
        /// </summary>
        public static string lbtiledoanhthuvungmien {
            get {
                return ResourceManager.GetString("lbtiledoanhthuvungmien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string lbtimkiem {
            get {
                return ResourceManager.GetString("lbtimkiem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỔNG DOANH THU.
        /// </summary>
        public static string lbtongdoanhthu {
            get {
                return ResourceManager.GetString("lbtongdoanhthu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỔNG TIỀN TOP.
        /// </summary>
        public static string lbtongtientop {
            get {
                return ResourceManager.GetString("lbtongtientop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho.
        /// </summary>
        public static string lbtonkho {
            get {
                return ResourceManager.GetString("lbtonkho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho SL-HD.
        /// </summary>
        public static string lbtonkhosolohandung {
            get {
                return ResourceManager.GetString("lbtonkhosolohandung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tồn kho tổng.
        /// </summary>
        public static string lbtonkhotong {
            get {
                return ResourceManager.GetString("lbtonkhotong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top doanh thu khách hàng.
        /// </summary>
        public static string lbtopdoanhthukh {
            get {
                return ResourceManager.GetString("lbtopdoanhthukh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top doanh thu khu vực.
        /// </summary>
        public static string lbtopdoanhthukhuvuc {
            get {
                return ResourceManager.GetString("lbtopdoanhthukhuvuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top doanh thu mã hàng hóa.
        /// </summary>
        public static string lbtopdoanhthumahh {
            get {
                return ResourceManager.GetString("lbtopdoanhthumahh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top hàng hóa.
        /// </summary>
        public static string lbtophanghoa {
            get {
                return ResourceManager.GetString("lbtophanghoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top khách hàng.
        /// </summary>
        public static string lbtopkhachhang {
            get {
                return ResourceManager.GetString("lbtopkhachhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top khu vực.
        /// </summary>
        public static string lbtopkhuvuc {
            get {
                return ResourceManager.GetString("lbtopkhuvuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string lbtrangchu {
            get {
                return ResourceManager.GetString("lbtrangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trừ tiền chiết khấu.
        /// </summary>
        public static string lbtruchietkhau {
            get {
                return ResourceManager.GetString("lbtruchietkhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ ngày.
        /// </summary>
        public static string lbtungay {
            get {
                return ResourceManager.GetString("lbtungay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Từ tháng.
        /// </summary>
        public static string lbtuthang {
            get {
                return ResourceManager.GetString("lbtuthang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Về trang chủ.
        /// </summary>
        public static string lbvetrangchu {
            get {
                return ResourceManager.GetString("lbvetrangchu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng điền đầy đủ thông tin tài khoản và mật khẩu !.
        /// </summary>
        public static string lbvuilongdienthongtin {
            get {
                return ResourceManager.GetString("lbvuilongdienthongtin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên tài khoản !.
        /// </summary>
        public static string lbvuilongnhaptentaikhoan {
            get {
                return ResourceManager.GetString("lbvuilongnhaptentaikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string lbxem {
            get {
                return ResourceManager.GetString("lbxem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem.
        /// </summary>
        public static string lbxemtructiep {
            get {
                return ResourceManager.GetString("lbxemtructiep", resourceCulture);
            }
        }
    }
}
